package main

import (
	"fmt"

	eb "github.com/hajimehoshi/ebiten"
)

//Liste de clés
var keysList = []eb.Key{
	eb.Key0,
	eb.Key1,
	eb.Key2,
	eb.Key3,
	eb.Key4,
	eb.Key5,
	eb.Key6,
	eb.Key7,
	eb.Key8,
	eb.Key9,
	eb.KeyA,
	eb.KeyB,
	eb.KeyC,
	eb.KeyD,
	eb.KeyE,
	eb.KeyF,
	eb.KeyG,
	eb.KeyH,
	eb.KeyI,
	eb.KeyJ,
	eb.KeyK,
	eb.KeyL,
	eb.KeyM,
	eb.KeyN,
	eb.KeyO,
	eb.KeyP,
	eb.KeyQ,
	eb.KeyR,
	eb.KeyS,
	eb.KeyT,
	eb.KeyU,
	eb.KeyV,
	eb.KeyW,
	eb.KeyX,
	eb.KeyY,
	eb.KeyZ,
	eb.KeyApostrophe,
	eb.KeyBackslash,
	eb.KeyBackspace,
	eb.KeyCapsLock,
	eb.KeyComma,
	eb.KeyDelete,
	eb.KeyDown,
	eb.KeyEnd,
	eb.KeyEnter,
	eb.KeyEqual,
	eb.KeyEscape,
	eb.KeyF1,
	eb.KeyF2,
	eb.KeyF3,
	eb.KeyF4,
	eb.KeyF5,
	eb.KeyF6,
	eb.KeyF7,
	eb.KeyF8,
	eb.KeyF9,
	eb.KeyF10,
	eb.KeyF11,
	eb.KeyF12,
	eb.KeyGraveAccent,
	eb.KeyHome,
	eb.KeyInsert,
	eb.KeyKP0,
	eb.KeyKP1,
	eb.KeyKP2,
	eb.KeyKP3,
	eb.KeyKP4,
	eb.KeyKP5,
	eb.KeyKP6,
	eb.KeyKP7,
	eb.KeyKP8,
	eb.KeyKP9,
	eb.KeyKPAdd,
	eb.KeyKPDecimal,
	eb.KeyKPDivide,
	eb.KeyKPEnter,
	eb.KeyKPEqual,
	eb.KeyKPMultiply,
	eb.KeyKPSubtract,
	eb.KeyLeft,
	eb.KeyAlt,
	eb.KeyLeftBracket,
	eb.KeyControl,
	eb.KeyShift,
	eb.KeyMenu,
	eb.KeyMinus,
	eb.KeyNumLock,
	eb.KeyPageDown,
	eb.KeyPageUp,
	eb.KeyPause,
	eb.KeyPeriod,
	eb.KeyPrintScreen,
	eb.KeyRight,
	eb.KeyRightBracket,
	eb.KeyScrollLock,
	eb.KeySemicolon,
	eb.KeySlash,
	eb.KeySpace,
	eb.KeyTab,
	eb.KeyUp,
}

//UsToFr mapping clé Us vers Fr
var UsToFr = map[eb.Key]eb.Key{
	eb.Key0:            eb.Key0,
	eb.Key1:            eb.Key1,
	eb.Key2:            eb.Key2,
	eb.Key3:            eb.Key3,
	eb.Key4:            eb.Key4,
	eb.Key5:            eb.Key5,
	eb.Key6:            eb.Key6,
	eb.Key7:            eb.Key7,
	eb.Key8:            eb.Key8,
	eb.Key9:            eb.Key9,
	eb.KeyA:            eb.KeyQ,
	eb.KeyB:            eb.KeyB,
	eb.KeyC:            eb.KeyC,
	eb.KeyD:            eb.KeyD,
	eb.KeyE:            eb.KeyE,
	eb.KeyF:            eb.KeyF,
	eb.KeyG:            eb.KeyG,
	eb.KeyH:            eb.KeyH,
	eb.KeyI:            eb.KeyI,
	eb.KeyJ:            eb.KeyJ,
	eb.KeyK:            eb.KeyK,
	eb.KeyL:            eb.KeyL,
	eb.KeyM:            eb.KeyComma,
	eb.KeyN:            eb.KeyN,
	eb.KeyO:            eb.KeyO,
	eb.KeyP:            eb.KeyP,
	eb.KeyQ:            eb.KeyA,
	eb.KeyR:            eb.KeyR,
	eb.KeyS:            eb.KeyS,
	eb.KeyT:            eb.KeyT,
	eb.KeyU:            eb.KeyU,
	eb.KeyV:            eb.KeyV,
	eb.KeyW:            eb.KeyZ,
	eb.KeyX:            eb.KeyX,
	eb.KeyY:            eb.KeyY,
	eb.KeyZ:            eb.KeyW,
	eb.KeyApostrophe:   eb.KeyApostrophe,
	eb.KeyBackslash:    eb.KeyEqual,
	eb.KeyBackspace:    eb.KeyBackspace,
	eb.KeyCapsLock:     eb.KeyCapsLock,
	eb.KeyComma:        eb.KeyM,
	eb.KeyDelete:       eb.KeyDelete,
	eb.KeyDown:         eb.KeyDown,
	eb.KeyEnd:          eb.KeyEnd,
	eb.KeyEnter:        eb.KeyEnter,
	eb.KeyEqual:        eb.KeyBackslash,
	eb.KeyEscape:       eb.KeyEscape,
	eb.KeyF1:           eb.KeyF1,
	eb.KeyF2:           eb.KeyF2,
	eb.KeyF3:           eb.KeyF3,
	eb.KeyF4:           eb.KeyF4,
	eb.KeyF5:           eb.KeyF5,
	eb.KeyF6:           eb.KeyF6,
	eb.KeyF7:           eb.KeyF7,
	eb.KeyF8:           eb.KeyF8,
	eb.KeyF9:           eb.KeyF9,
	eb.KeyF10:          eb.KeyF10,
	eb.KeyF11:          eb.KeyF11,
	eb.KeyF12:          eb.KeyF12,
	eb.KeyGraveAccent:  eb.KeyGraveAccent,
	eb.KeyHome:         eb.KeyHome,
	eb.KeyInsert:       eb.KeyInsert,
	eb.KeyKP0:          eb.KeyKP0,
	eb.KeyKP1:          eb.KeyKP1,
	eb.KeyKP2:          eb.KeyKP2,
	eb.KeyKP3:          eb.KeyKP3,
	eb.KeyKP4:          eb.KeyKP4,
	eb.KeyKP5:          eb.KeyKP5,
	eb.KeyKP6:          eb.KeyKP6,
	eb.KeyKP7:          eb.KeyKP7,
	eb.KeyKP8:          eb.KeyKP8,
	eb.KeyKP9:          eb.KeyKP9,
	eb.KeyKPAdd:        eb.KeyKPAdd,
	eb.KeyKPDecimal:    eb.KeyKPDecimal,
	eb.KeyKPDivide:     eb.KeyKPDivide,
	eb.KeyKPEnter:      eb.KeyKPEnter,
	eb.KeyKPEqual:      eb.KeyKPEqual,
	eb.KeyKPMultiply:   eb.KeyKPMultiply,
	eb.KeyKPSubtract:   eb.KeyKPSubtract,
	eb.KeyLeft:         eb.KeyLeft,
	eb.KeyAlt:          eb.KeyAlt,
	eb.KeyLeftBracket:  eb.KeyLeftBracket,
	eb.KeyControl:      eb.KeyControl,
	eb.KeyShift:        eb.KeyShift,
	eb.KeyMenu:         eb.KeyMenu,
	eb.KeyMinus:        eb.KeyMinus,
	eb.KeyNumLock:      eb.KeyNumLock,
	eb.KeyPageDown:     eb.KeyPageDown,
	eb.KeyPageUp:       eb.KeyPageUp,
	eb.KeyPause:        eb.KeyPause,
	eb.KeyPeriod:       eb.KeyPeriod,
	eb.KeyPrintScreen:  eb.KeyPrintScreen,
	eb.KeyRight:        eb.KeyRight,
	eb.KeyRightBracket: eb.KeyRightBracket,
	eb.KeyScrollLock:   eb.KeyScrollLock,
	eb.KeySemicolon:    eb.KeySemicolon,
	eb.KeySlash:        eb.KeySlash,
	eb.KeySpace:        eb.KeySpace,
	eb.KeyTab:          eb.KeyTab,
	eb.KeyUp:           eb.KeyUp,
}

//FrtoUs Mapping clé layout Fr vers Us
var FrtoUs = map[eb.Key]eb.Key{
	eb.Key0:            eb.Key0,
	eb.Key1:            eb.Key1,
	eb.Key2:            eb.Key2,
	eb.Key3:            eb.Key3,
	eb.Key4:            eb.Key4,
	eb.Key5:            eb.Key5,
	eb.Key6:            eb.Key6,
	eb.Key7:            eb.Key7,
	eb.Key8:            eb.Key8,
	eb.Key9:            eb.Key9,
	eb.KeyA:            eb.KeyA,
	eb.KeyB:            eb.KeyB,
	eb.KeyC:            eb.KeyC,
	eb.KeyD:            eb.KeyD,
	eb.KeyE:            eb.KeyE,
	eb.KeyF:            eb.KeyF,
	eb.KeyG:            eb.KeyG,
	eb.KeyH:            eb.KeyH,
	eb.KeyI:            eb.KeyI,
	eb.KeyJ:            eb.KeyJ,
	eb.KeyK:            eb.KeyK,
	eb.KeyL:            eb.KeyL,
	eb.KeyM:            eb.KeyM,
	eb.KeyN:            eb.KeyN,
	eb.KeyO:            eb.KeyO,
	eb.KeyP:            eb.KeyP,
	eb.KeyQ:            eb.KeyQ,
	eb.KeyR:            eb.KeyR,
	eb.KeyS:            eb.KeyS,
	eb.KeyT:            eb.KeyT,
	eb.KeyU:            eb.KeyU,
	eb.KeyV:            eb.KeyV,
	eb.KeyW:            eb.KeyW,
	eb.KeyX:            eb.KeyX,
	eb.KeyY:            eb.KeyY,
	eb.KeyZ:            eb.KeyZ,
	eb.KeyApostrophe:   eb.KeyApostrophe,
	eb.KeyBackslash:    eb.KeyBackslash,
	eb.KeyBackspace:    eb.KeyBackspace,
	eb.KeyCapsLock:     eb.KeyCapsLock,
	eb.KeyComma:        eb.KeyComma,
	eb.KeyDelete:       eb.KeyDelete,
	eb.KeyDown:         eb.KeyDown,
	eb.KeyEnd:          eb.KeyEnd,
	eb.KeyEnter:        eb.KeyEnter,
	eb.KeyEqual:        eb.KeyEqual,
	eb.KeyEscape:       eb.KeyEscape,
	eb.KeyF1:           eb.KeyF1,
	eb.KeyF2:           eb.KeyF2,
	eb.KeyF3:           eb.KeyF3,
	eb.KeyF4:           eb.KeyF4,
	eb.KeyF5:           eb.KeyF5,
	eb.KeyF6:           eb.KeyF6,
	eb.KeyF7:           eb.KeyF7,
	eb.KeyF8:           eb.KeyF8,
	eb.KeyF9:           eb.KeyF9,
	eb.KeyF10:          eb.KeyF10,
	eb.KeyF11:          eb.KeyF11,
	eb.KeyF12:          eb.KeyF12,
	eb.KeyGraveAccent:  eb.KeyGraveAccent,
	eb.KeyHome:         eb.KeyHome,
	eb.KeyInsert:       eb.KeyInsert,
	eb.KeyKP0:          eb.KeyKP0,
	eb.KeyKP1:          eb.KeyKP1,
	eb.KeyKP2:          eb.KeyKP2,
	eb.KeyKP3:          eb.KeyKP3,
	eb.KeyKP4:          eb.KeyKP4,
	eb.KeyKP5:          eb.KeyKP5,
	eb.KeyKP6:          eb.KeyKP6,
	eb.KeyKP7:          eb.KeyKP7,
	eb.KeyKP8:          eb.KeyKP8,
	eb.KeyKP9:          eb.KeyKP9,
	eb.KeyKPAdd:        eb.KeyKPAdd,
	eb.KeyKPDecimal:    eb.KeyKPDecimal,
	eb.KeyKPDivide:     eb.KeyKPDivide,
	eb.KeyKPEnter:      eb.KeyKPEnter,
	eb.KeyKPEqual:      eb.KeyKPEqual,
	eb.KeyKPMultiply:   eb.KeyKPMultiply,
	eb.KeyKPSubtract:   eb.KeyKPSubtract,
	eb.KeyLeft:         eb.KeyLeft,
	eb.KeyAlt:          eb.KeyAlt,
	eb.KeyLeftBracket:  eb.KeyLeftBracket,
	eb.KeyControl:      eb.KeyControl,
	eb.KeyShift:        eb.KeyShift,
	eb.KeyMenu:         eb.KeyMenu,
	eb.KeyMinus:        eb.KeyMinus,
	eb.KeyNumLock:      eb.KeyNumLock,
	eb.KeyPageDown:     eb.KeyPageDown,
	eb.KeyPageUp:       eb.KeyPageUp,
	eb.KeyPause:        eb.KeyPause,
	eb.KeyPeriod:       eb.KeyPeriod,
	eb.KeyPrintScreen:  eb.KeyPrintScreen,
	eb.KeyRight:        eb.KeyRight,
	eb.KeyRightBracket: eb.KeyRightBracket,
	eb.KeyScrollLock:   eb.KeyScrollLock,
	eb.KeySemicolon:    eb.KeySemicolon,
	eb.KeySlash:        eb.KeySlash,
	eb.KeySpace:        eb.KeySpace,
	eb.KeyTab:          eb.KeyTab,
	eb.KeyUp:           eb.KeyUp,
}

func printKey() {
	for _, k := range keysList {
		if eb.IsKeyPressed(k) {
			fmt.Println(k.String())
		}
	}
}
